const MONTHS=['January','February','March','April','May','June','July','August','September','October','November','December'];
const DOW=['Mo','Tu','We','Th','Fr','Sa','Su'];
const DEFAULT_CATS=[
 {id:'holiday',name:'Holidays / Organization Days',color:'#7c8795'},
 {id:'deadline',name:'Grant Events / Deadlines',color:'#b48245'},
 {id:'site',name:'Site Visits',color:'#6d5f8f'},
 {id:'meeting',name:'Grant Meetings / Trainings',color:'#3f718c'}
];
let state={version:1,name:'FY27 Grant & Organization Calendar',fiscalYear:2027,fyStart:6,pageSize:'Letter',calendarYears:[2026,2027],federalHolidays:true,categories:structuredClone(DEFAULT_CATS),events:[]};
let previewMode='fy';
const $=id=>document.getElementById(id), esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const uid=()=>crypto.randomUUID?crypto.randomUUID():Date.now().toString(36)+Math.random().toString(36).slice(2);
function download(blob,name){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1500)}
function cat(id){return state.categories.find(c=>c.id===id)||{name:'Uncategorized',color:'#999'} }
function dateISO(y,m,d){return `${y}-${String(m+1).padStart(2,'0')}-${String(d).padStart(2,'0')}`}
function parseISO(s){if(!s)return null;const [y,m,d]=s.slice(0,10).split('-').map(Number);return new Date(y,m-1,d)}
function fmt(s){const d=parseISO(s);return d?d.toLocaleDateString('en-US',{month:'short',day:'numeric',year:'numeric'}):''}
function sanitizeName(s){return (s||'Grant_Calendar').replace(/[^a-z0-9_-]+/gi,'_').replace(/^_+|_+$/g,'')}
function init(){MONTHS.forEach((m,i)=>$('fyStart').add(new Option(m,i)));$('fyStart').value=6;bind();syncSetup();renderCategories();renderEvents();renderPreviewControls();renderPreview();}
function bind(){document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>show(b.dataset.view));document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>show(b.dataset.go));
 ['calendarName','fiscalYear','fyStart','pageSize','holidays'].forEach(id=>$(id).addEventListener('change',readSetup));
 $('addCat').onclick=()=>{state.categories.push({id:uid(),name:'New Category',color:'#52718f'});renderCategories();syncSelects();};
 $('addEvent').onclick=()=>openEvent();$('closeModal').onclick=$('cancelModal').onclick=closeEvent;$('eventForm').onsubmit=saveEvent;$('eventCat').onchange=siteForm;$('eventStatus').onchange=siteForm;$('deleteEvent').onclick=deleteCurrent;
 $('search').oninput=$('catFilter').onchange=$('statusFilter').onchange=renderEvents;
 $('saveBtn').onclick=$('saveBtn2').onclick=saveProject;$('openBtn').onclick=()=>$('projectFile').click();$('projectFile').onchange=openProject;
 $('importBtn').onclick=()=>$('importFile').click();$('importFile').onchange=importEvents;$('templateBtn').onclick=$('templateBtn2').onclick=downloadTemplate;
 document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{previewMode=b.dataset.mode;document.querySelectorAll('[data-mode]').forEach(x=>x.classList.toggle('active',x===b));renderPreviewControls();renderPreview()});
 $('previewYear').onchange=$('previewMonth').onchange=renderPreview;$('xlsxBtn').onclick=exportWorkbook;$('clipboardBtn').onclick=exportClipboard;
 $('closeOutlook').onclick=$('cancelOutlook').onclick=()=>$('outlookModal').classList.add('hidden');$('outlookForm').onsubmit=downloadICS;
}
function show(id){document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.id===id));document.querySelectorAll('#steps button').forEach(b=>b.classList.toggle('active',b.dataset.view===id));if(id==='preview'){renderPreviewControls();renderPreview()}window.scrollTo({top:0,behavior:'smooth'})}
function syncSetup(){$('calendarName').value=state.name;$('fiscalYear').value=state.fiscalYear;$('fyStart').value=state.fyStart;$('pageSize').value=state.pageSize;$('holidays').checked=state.federalHolidays;renderCYChecks();updateHero();syncSelects()}
function readSetup(){state.name=$('calendarName').value.trim()||'Grant Calendar';state.fiscalYear=+$('fiscalYear').value||new Date().getFullYear();state.fyStart=+$('fyStart').value;state.pageSize=$('pageSize').value;state.federalHolidays=$('holidays').checked;const startYear=state.fiscalYear-(state.fyStart===0?0:1);const yrs=[startYear,state.fiscalYear];state.calendarYears=[...new Set([...state.calendarYears.filter(y=>yrs.includes(y)),...yrs])].sort();renderCYChecks();updateHero();renderPreviewControls()}
function renderCYChecks(){const startYear=state.fiscalYear-(state.fyStart===0?0:1);const opts=[...new Set([startYear,state.fiscalYear,...state.calendarYears])].sort();$('cyChecks').innerHTML=opts.map(y=>`<label class="toggle"><input type="checkbox" data-cy="${y}" ${state.calendarYears.includes(y)?'checked':''}> ${y}</label>`).join('');document.querySelectorAll('[data-cy]').forEach(x=>x.onchange=()=>{state.calendarYears=[...document.querySelectorAll('[data-cy]:checked')].map(x=>+x.dataset.cy).sort();renderPreviewControls()})}
function updateHero(){const sy=state.fiscalYear-(state.fyStart===0?0:1), ey=state.fyStart===0?sy:state.fiscalYear;$('heroName').textContent=state.name;$('heroMeta').textContent=`FY ${state.fiscalYear} · ${MONTHS[state.fyStart]} ${sy} – ${MONTHS[(state.fyStart+11)%12]} ${ey} · ${state.events.length} Events`}
function renderCategories(){$('categoryList').innerHTML=state.categories.map(c=>`<div class="catrow"><input type="color" value="${c.color}" data-color="${c.id}"><input value="${esc(c.name)}" data-catname="${c.id}"><button data-delcat="${c.id}" title="Delete">×</button></div>`).join('');document.querySelectorAll('[data-color]').forEach(x=>x.oninput=()=>{cat(x.dataset.color).color=x.value;renderEvents()});document.querySelectorAll('[data-catname]').forEach(x=>x.onchange=()=>{cat(x.dataset.catname).name=x.value.trim()||'Category';syncSelects();renderEvents()});document.querySelectorAll('[data-delcat]').forEach(x=>x.onclick=()=>{if(state.events.some(e=>e.categoryId===x.dataset.delcat))return alert('Reassign or delete events in this category first.');state.categories=state.categories.filter(c=>c.id!==x.dataset.delcat);renderCategories();syncSelects()});syncSelects()}
function syncSelects(){const options=state.categories.map(c=>`<option value="${c.id}">${esc(c.name)}</option>`).join('');$('eventCat').innerHTML=options;$('catFilter').innerHTML='<option value="">All Categories</option>'+options}
function openEvent(id){const e=id?state.events.find(e=>e.id===id):null;$('modalTitle').textContent=e?'Edit Event':'Add Event';$('eventId').value=e?.id||'';$('eventName').value=e?.name||'';$('org').value=e?.org||'';$('eventCat').value=e?.categoryId||state.categories[1]?.id||state.categories[0]?.id;$('eventStatus').value=e?.status||'confirmed';$('startDate').value=e?.startDate||'';$('endDate').value=e?.endDate||'';$('description').value=e?.description||'';$('notes').value=e?.notes||'';$('marker').checked=e?.marker!==false;$('annual').checked=e?.annual!==false;$('deleteEvent').classList.toggle('hidden',!e);siteForm();$('modal').classList.remove('hidden')}
function closeEvent(){$('modal').classList.add('hidden')}
function isSiteCat(id){return id==='site'||/site visit/i.test(cat(id).name)}
function siteForm(){const site=isSiteCat($('eventCat').value),tent=$('eventStatus').value==='tentative';$('siteHelp').classList.toggle('hidden',!site);$('startLabel').childNodes[0].nodeValue=site&&tent?'Window start*':'Start date*';$('endLabel').childNodes[0].nodeValue=site&&tent?'Window end*':'End date';$('endDate').required=site&&tent;if(site&&!tent){$('endDate').value='';$('endDate').disabled=true}else $('endDate').disabled=false}
function saveEvent(ev){ev.preventDefault();const obj={id:$('eventId').value||uid(),name:$('eventName').value.trim(),org:$('org').value.trim(),categoryId:$('eventCat').value,status:$('eventStatus').value,startDate:$('startDate').value,endDate:$('endDate').value,description:$('description').value.trim(),notes:$('notes').value.trim(),marker:$('marker').checked,annual:$('annual').checked};if(isSiteCat(obj.categoryId)&&obj.status!=='tentative')obj.endDate='';const i=state.events.findIndex(e=>e.id===obj.id);if(i>=0)state.events[i]=obj;else state.events.push(obj);closeEvent();renderEvents();updateHero()}
function deleteCurrent(){const id=$('eventId').value;if(confirm('Delete this event?')){state.events=state.events.filter(e=>e.id!==id);closeEvent();renderEvents();updateHero()}}
function renderEvents(){const q=$('search').value.toLowerCase(),cf=$('catFilter').value,sf=$('statusFilter').value;const rows=state.events.filter(e=>(!q||`${e.name} ${e.org}`.toLowerCase().includes(q))&&(!cf||e.categoryId===cf)&&(!sf||e.status===sf)).sort((a,b)=>a.startDate.localeCompare(b.startDate));$('eventSummary').textContent=`${state.events.length} total · ${state.events.filter(e=>e.status==='confirmed').length} confirmed · ${state.events.filter(e=>e.status==='tentative').length} tentative · ${state.events.filter(e=>e.status==='cancelled').length} cancelled`;$('eventRows').innerHTML=rows.length?rows.map(e=>`<tr class="${e.status==='cancelled'?'cancelled':''}"><td>${fmt(e.startDate)}${e.endDate?` – ${fmt(e.endDate)}`:''}</td><td><b>${esc(e.name)}</b></td><td>${esc(e.org)}</td><td><span class="pill" style="background:${cat(e.categoryId).color}22;color:${cat(e.categoryId).color}">${esc(cat(e.categoryId).name)}</span></td><td>${e.status}</td><td>${e.annual?'✓':'—'}</td><td><div class="actions"><button onclick="openEvent('${e.id}')">Edit</button>${isSiteCat(e.categoryId)&&e.status==='tentative'?`<button onclick="assignSite('${e.id}')">Assign Date</button><button onclick="cancelSite('${e.id}')">Cancel</button>`:''}${e.status!=='cancelled'?`<button onclick="openOutlook('${e.id}')">Outlook Event</button>`:''}</div></td></tr>`).join(''):`<tr><td colspan="7" style="text-align:center;padding:40px;color:#7a8794">No events yet. Add one or import the template.</td></tr>`}
window.openEvent=openEvent;window.assignSite=id=>{const e=state.events.find(x=>x.id===id);const d=prompt(`Assign the exact one-day Site Visit date.\nCurrent window: ${fmt(e.startDate)} – ${fmt(e.endDate)}\n\nEnter YYYY-MM-DD:`);if(!d)return;if(!/^\d{4}-\d{2}-\d{2}$/.test(d))return alert('Please use YYYY-MM-DD.');if((d<e.startDate||d>e.endDate)&&!confirm('This date is outside the original window. Use it anyway?'))return;e.startDate=d;e.endDate='';e.status='confirmed';renderEvents();renderPreview()};window.cancelSite=id=>{const e=state.events.find(x=>x.id===id);if(confirm('Cancel this Site Visit? It will remain in the project but be excluded from calendar output.')){e.status='cancelled';renderEvents();renderPreview()}};
function activeEvents(includeTent=true){let arr=state.events.filter(e=>e.status!=='cancelled'&&(includeTent||e.status==='confirmed'));if(state.federalHolidays){state.calendarYears.forEach(y=>arr.push(...holidaysFor(y)))}return arr}
function holidayObj(name,date){return{id:`h-${date}-${name}`,name,org:'U.S. Federal Holiday',categoryId:'holiday',status:'confirmed',startDate:date,endDate:'',description:'',notes:'',marker:true,annual:true,system:true}}
function nthWeekday(y,m,weekday,n){let d=new Date(y,m,1);while(d.getDay()!==weekday)d.setDate(d.getDate()+1);d.setDate(d.getDate()+7*(n-1));return dateISO(y,m,d.getDate())}function lastWeekday(y,m,weekday){let d=new Date(y,m+1,0);while(d.getDay()!==weekday)d.setDate(d.getDate()-1);return dateISO(y,m,d.getDate())}function observed(y,m,d){const x=new Date(y,m,d),w=x.getDay();if(w===6)x.setDate(x.getDate()-1);if(w===0)x.setDate(x.getDate()+1);return dateISO(x.getFullYear(),x.getMonth(),x.getDate())}
function holidaysFor(y){return[holidayObj("New Year's Day",observed(y,0,1)),holidayObj('Martin Luther King Jr. Day',nthWeekday(y,0,1,3)),holidayObj("Washington's Birthday",nthWeekday(y,1,1,3)),holidayObj('Memorial Day',lastWeekday(y,4,1)),holidayObj('Juneteenth National Independence Day',observed(y,5,19)),holidayObj('Independence Day',observed(y,6,4)),holidayObj('Labor Day',nthWeekday(y,8,1,1)),holidayObj('Columbus Day',nthWeekday(y,9,1,2)),holidayObj('Veterans Day',observed(y,10,11)),holidayObj('Thanksgiving Day',nthWeekday(y,10,4,4)),holidayObj('Christmas Day',observed(y,11,25))]}
function eventsOn(y,m,d){const ds=dateISO(y,m,d);return activeEvents().filter(e=>e.startDate<=ds&&(e.endDate||e.startDate)>=ds)}
function monthHTML(y,m,detail=true,monthly=false){const first=new Date(y,m,1),days=new Date(y,m+1,0).getDate(),offset=(first.getDay()+6)%7;let cells=[];for(let i=0;i<offset;i++)cells.push('<div class="day"></div>');for(let d=1;d<=days;d++){const ev=eventsOn(y,m,d);cells.push(`<div class="day"><b>${d}</b><div class="markers">${ev.filter(e=>e.marker).map(e=>`<span class="marker" title="${esc(e.name)}" style="background:${cat(e.categoryId).color}"></span>`).join('')}</div></div>`)}while(cells.length%7)cells.push('<div class="day"></div>');const weeks=[];for(let i=0;i<cells.length;i+=7)weeks.push(`<div class="week">${cells.slice(i,i+7).join('')}</div>`);const monthEvents=activeEvents().filter(e=>e.startDate.slice(0,7)===`${y}-${String(m+1).padStart(2,'0')}`&&e.annual).sort((a,b)=>a.startDate.localeCompare(b.startDate));let details='';if(detail&&monthEvents.length){details='<div class="details">'+monthEvents.map(e=>`<div><span style="color:${cat(e.categoryId).color}">■</span> ${parseISO(e.startDate).getDate()} — ${esc(e.name)}</div>`).join('')+'</div>'}return `<div class="monthbox ${monthly?'monthly':''}"><div class="monthtitle">${MONTHS[m]} ${y}</div><div class="dow">${DOW.map(x=>`<div>${x}</div>`).join('')}</div>${weeks.join('')}${details}</div>`}
function fyMonths(){const sy=state.fiscalYear-(state.fyStart===0?0:1);return Array.from({length:12},(_,i)=>{const mm=(state.fyStart+i)%12, yy=sy+Math.floor((state.fyStart+i)/12);return[yy,mm]})}
function renderPreviewControls(){const yrs=state.calendarYears.length?state.calendarYears:[state.fiscalYear];$('previewYear').innerHTML=yrs.map(y=>`<option>${y}</option>`).join('');$('previewMonth').innerHTML=MONTHS.map((m,i)=>`<option value="${i}">${m}</option>`).join('');$('previewYear').style.display=previewMode==='fy'?'none':'';$('previewMonth').style.display=previewMode==='month'?'':'none'}
function renderPreview(){let html='',count=0;if(previewMode==='fy'){const ms=fyMonths();html=`<div class="yeargrid">${ms.map(([y,m])=>monthHTML(y,m,true)).join('')}</div>`;count=activeEvents().filter(e=>e.annual&&fyDateIn(e.startDate)).length}else if(previewMode==='cy'){const y=+$('previewYear').value||state.calendarYears[0];html=`<div class="yeargrid">${MONTHS.map((_,m)=>monthHTML(y,m,true)).join('')}</div>`;count=activeEvents().filter(e=>e.annual&&e.startDate.startsWith(y+'-')).length}else{const y=+$('previewYear').value||state.calendarYears[0],m=+$('previewMonth').value;html=`<div class="monthly">${monthHTML(y,m,false,true)}${monthlyDetails(y,m)}</div>`;count=0}$('calendarPreview').innerHTML=html;const box=$('fitBox');if(previewMode==='month'){box.className='fit good';box.textContent='Monthly view · Event details are placed beneath the calendar in the Excel output.'}else{const level=count<=28?'good':count<=45?'tight':'bad';box.className='fit '+level;box.textContent=level==='good'?`One-page fit: Good · ${count} annual-detail entries.`:level==='tight'?`One-page fit: Tight · ${count} annual-detail entries. Consider hiding lower-priority annual details.`:`One-page fit unlikely · ${count} annual-detail entries. Category markers will remain if you hide some annual details.`}}
function fyDateIn(s){const [[sy,sm],[ey,em]]= [fyMonths()[0],fyMonths()[11]];return s>=dateISO(sy,sm,1)&&s<=dateISO(ey,em,new Date(ey,em+1,0).getDate())}
function monthlyDetails(y,m){const pre=`${y}-${String(m+1).padStart(2,'0')}`;const es=activeEvents().filter(e=>e.startDate.startsWith(pre)).sort((a,b)=>a.startDate.localeCompare(b.startDate));if(!es.length)return '<div class="details"><b>Event Details</b><p>No events for this month.</p></div>';return `<div class="details"><h3>Event Details</h3>${state.categories.map(c=>{const x=es.filter(e=>e.categoryId===c.id);return x.length?`<h4 style="color:${c.color}">${esc(c.name)}</h4>${x.map(e=>`<p><b>${fmt(e.startDate)} — ${esc(e.name)}</b>${e.org?` · ${esc(e.org)}`:''}${e.description?`<br>${esc(e.description)}`:''}</p>`).join('')}`:''}).join('')}</div>`}
function saveProject(){readSetup();download(new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),`${sanitizeName(state.name)}.json`)}
async function openProject(ev){const f=ev.target.files[0];if(!f)return;try{const x=JSON.parse(await f.text());if(!x.categories||!x.events)throw 0;state=x;syncSetup();renderCategories();renderEvents();renderPreviewControls();renderPreview()}catch{alert('That project file could not be opened.')}ev.target.value=''}
async function importEvents(ev){const f=ev.target.files[0];if(!f)return;if(!window.ExcelJS){alert('Excel library failed to load. Check your internet connection.');return}try{const wb=new ExcelJS.Workbook();await wb.xlsx.load(await f.arrayBuffer());const ws=wb.getWorksheet('Events')||wb.worksheets[0];const headers={};ws.getRow(1).eachCell((c,n)=>headers[String(c.value).trim().toLowerCase()]=n);let added=0,dups=0,errors=0;for(let r=2;r<=ws.rowCount;r++){const row=ws.getRow(r);const val=k=>row.getCell(headers[k]||0).value;const name=String(val('event name')||'').trim();if(!name)continue;const cv=String(val('category')||'').trim(), category=state.categories.find(c=>c.name.toLowerCase()===cv.toLowerCase())||state.categories[1]||state.categories[0];const sd=excelDate(val('start date')),ed=excelDate(val('end date'));if(!sd){errors++;continue}const obj={id:uid(),name,org:String(val('grant / organization')||'').trim(),categoryId:category.id,status:String(val('status')||'confirmed').toLowerCase(),startDate:sd,endDate:ed,description:String(val('description')||'').trim(),notes:String(val('notes')||'').trim(),marker:yes(val('show marker'),true),annual:yes(val('include in annual view'),true)};const dup=state.events.find(e=>e.name.toLowerCase()===name.toLowerCase()&&e.startDate===sd);if(dup){dups++;const action=confirm(`Possible duplicate:\n${name} — ${fmt(sd)}\n\nOK = keep both\nCancel = skip new`);if(!action)continue}state.events.push(obj);added++}alert(`Import complete.\n${added} added\n${dups} possible duplicate(s) reviewed\n${errors} row(s) skipped for missing/invalid dates`);renderEvents();updateHero()}catch(e){console.error(e);alert('Could not read this Excel file. Use the Calendar Tool import template.')}ev.target.value=''}
function yes(v,def){if(v==null||v==='')return def;return /^(yes|y|true|1)$/i.test(String(v))}function excelDate(v){if(!v)return'';if(v instanceof Date)return dateISO(v.getFullYear(),v.getMonth(),v.getDate());if(typeof v==='object'&&v.result)v=v.result;const d=new Date(v);if(!isNaN(d))return dateISO(d.getFullYear(),d.getMonth(),d.getDate());return''}
async function downloadTemplate(){if(!window.ExcelJS)return alert('Excel library failed to load.');const wb=new ExcelJS.Workbook(),ws=wb.addWorksheet('Events'),ins=wb.addWorksheet('Instructions');ws.addRow(['Event Name','Grant / Organization','Category','Status','Start Date','End Date','Description','Notes','Show Marker','Include in Annual View']);ws.getRow(1).font={bold:true,color:{argb:'FFFFFFFF'}};ws.getRow(1).fill={type:'pattern',pattern:'solid',fgColor:{argb:'FF0D223B'}};ws.columns=[28,22,28,14,14,14,38,38,14,22].map(width=>({width}));ws.views=[{state:'frozen',ySplit:1}];ins.addRows([['Codex Analytics — Grant Calendar Import Template'],['Enter one event per row on the Events sheet.'],['Dates','Use Excel dates or MM/DD/YYYY.'],['Site Visits','For a tentative site-visit window, Status = tentative and use Start Date + End Date.'],['Status','confirmed, tentative, or cancelled'],['Categories',state.categories.map(c=>c.name).join(' | ')],['Show Marker / Annual View','Yes or No. Blank defaults to Yes.'],['Import behavior','New imports add to existing events. Matching Event Name + Start Date triggers a duplicate review.']]);ins.getColumn(1).width=24;ins.getColumn(2).width=100;download(new Blob([await wb.xlsx.writeBuffer()],{type:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'}),'Codex_Grant_Calendar_Import_Template.xlsx')}
function openOutlook(id){const e=state.events.find(x=>x.id===id);$('outlookEventId').value=id;$('oTitle').value=e.name;$('oDate').value=e.startDate;$('oAllDay').checked=isSiteCat(e.categoryId)||/deadline|holiday/i.test(cat(e.categoryId).name);$('oStart').value='09:00';$('oEnd').value='10:00';$('oLocation').value='';$('oInvitees').value='';$('oDesc').value=[e.description,e.notes].filter(Boolean).join('\n\n');$('oReminder').value=$('oAllDay').checked?'1440':'15';$('outlookModal').classList.remove('hidden')}window.openOutlook=openOutlook;
function icsEscape(s){return String(s||'').replace(/\\/g,'\\\\').replace(/\n/g,'\\n').replace(/,/g,'\\,').replace(/;/g,'\\;')}function stamp(){return new Date().toISOString().replace(/[-:]/g,'').replace(/\.\d{3}/,'')}
function downloadICS(ev){ev.preventDefault();const allday=$('oAllDay').checked,d=$('oDate').value,title=$('oTitle').value,invitees=$('oInvitees').value.split(';').map(x=>x.trim()).filter(Boolean);let lines=['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//Codex Analytics//Grant Calendar Tool//EN','CALSCALE:GREGORIAN','METHOD:PUBLISH','BEGIN:VEVENT',`UID:${uid()}@codex-calendar`,`DTSTAMP:${stamp()}`,`SUMMARY:${icsEscape(title)}`];if(allday){const dt=d.replaceAll('-','');const nx=parseISO(d);nx.setDate(nx.getDate()+1);lines.push(`DTSTART;VALUE=DATE:${dt}`,`DTEND;VALUE=DATE:${dateISO(nx.getFullYear(),nx.getMonth(),nx.getDate()).replaceAll('-','')}`)}else{const t=s=>s.replace(':','')+'00';lines.push(`DTSTART:${d.replaceAll('-','')}T${t($('oStart').value||'09:00')}`,`DTEND:${d.replaceAll('-','')}T${t($('oEnd').value||'10:00')}`)}if($('oLocation').value)lines.push(`LOCATION:${icsEscape($('oLocation').value)}`);if($('oDesc').value)lines.push(`DESCRIPTION:${icsEscape($('oDesc').value)}`);invitees.forEach(x=>lines.push(`ATTENDEE;RSVP=TRUE:mailto:${x}`));const rem=+$('oReminder').value;if(rem)lines.push('BEGIN:VALARM',`TRIGGER:-PT${rem}M`,'ACTION:DISPLAY',`DESCRIPTION:${icsEscape(title)}`,'END:VALARM');lines.push('END:VEVENT','END:VCALENDAR');download(new Blob([lines.join('\r\n')],{type:'text/calendar'}),`${sanitizeName(title)}.ics`);$('outlookModal').classList.add('hidden')}
function excelColor(hex){return 'FF'+hex.replace('#','').toUpperCase()}function setCell(cell,value,opts={}){cell.value=value;if(opts.bold)cell.font={...(cell.font||{}),bold:true};if(opts.size)cell.font={...(cell.font||{}),size:opts.size};if(opts.color)cell.font={...(cell.font||{}),color:{argb:opts.color}};if(opts.fill)cell.fill={type:'pattern',pattern:'solid',fgColor:{argb:opts.fill}};cell.alignment={vertical:'middle',horizontal:opts.align||'center',wrapText:true};cell.border={top:{style:'thin',color:{argb:'FFD9DEE3'}},left:{style:'thin',color:{argb:'FFD9DEE3'}},bottom:{style:'thin',color:{argb:'FFD9DEE3'}},right:{style:'thin',color:{argb:'FFD9DEE3'}}}}
function buildMonthBlock(ws,y,m,startRow,startCol,annualDetails=true){ws.mergeCells(startRow,startCol,startRow,startCol+6);setCell(ws.getCell(startRow,startCol),`${MONTHS[m]} ${y}`,{bold:true,color:'FFFFFFFF',fill:'FF0D223B'});DOW.forEach((x,i)=>setCell(ws.getCell(startRow+1,startCol+i),x,{bold:true,fill:'FFECEFF2'}));const first=new Date(y,m,1),days=new Date(y,m+1,0).getDate(),off=(first.getDay()+6)%7;for(let d=1;d<=days;d++){const idx=off+d-1,r=startRow+2+Math.floor(idx/7),c=startCol+(idx%7),ev=eventsOn(y,m,d);let val=String(d);if(ev.length)val+='\n'+ev.filter(e=>e.marker).map(e=>'■').join(' ');setCell(ws.getCell(r,c),val,{align:'left'});if(ev.length){const firstEv=ev.find(e=>e.marker);if(firstEv)ws.getCell(r,c).font={size:9,color:{argb:excelColor(cat(firstEv.categoryId).color)}}}}const detailRow=startRow+8;ws.mergeCells(detailRow,startCol,detailRow+3,startCol+6);const es=activeEvents().filter(e=>e.annual&&e.startDate.slice(0,7)===`${y}-${String(m+1).padStart(2,'0')}`).sort((a,b)=>a.startDate.localeCompare(b.startDate));const txt=annualDetails?es.map(e=>`${parseISO(e.startDate).getDate()} — ${e.name}`).join('\n'):'';setCell(ws.getCell(detailRow,startCol),txt,{align:'left'});ws.getCell(detailRow,startCol).alignment={vertical:'top',horizontal:'left',wrapText:true};for(let c=startCol;c<startCol+7;c++)ws.getColumn(c).width=5.3}
async function exportWorkbook(){readSetup();if(!window.ExcelJS)return alert('Excel library failed to load.');const wb=new ExcelJS.Workbook();wb.creator='Codex Analytics — Office Hero Pack';wb.created=new Date();const cy=state.calendarYears[0]||state.fiscalYear;buildYearSheet(wb,'Calendar Year',MONTHS.map((_,m)=>[cy,m]));buildYearSheet(wb,'Fiscal Year',fyMonths());for(let m=0;m<12;m++)buildMonthlySheet(wb,MONTHS[m].slice(0,3),cy,m);const buf=await wb.xlsx.writeBuffer();download(new Blob([buf],{type:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'}),`${sanitizeName(state.name)}.xlsx`)}
function buildYearSheet(wb,name,months){const ws=wb.addWorksheet(name,{pageSetup:{orientation:'landscape',paperSize:state.pageSize==='Legal'?5:1,fitToPage:true,fitToWidth:1,fitToHeight:1,margins:{left:.25,right:.25,top:.35,bottom:.35,header:.15,footer:.15}}});ws.mergeCells(1,1,1,23);setCell(ws.getCell(1,1),`${state.name} — ${name}`,{bold:true,size:16,color:'FFFFFFFF',fill:'FF0D223B'});months.forEach(([y,m],i)=>{const row=3+Math.floor(i/3)*13,col=1+(i%3)*8;buildMonthBlock(ws,y,m,row,col,true)});ws.mergeCells(55,1,55,23);setCell(ws.getCell(55,1),state.categories.map(c=>`■ ${c.name}`).join('     '),{align:'center'});ws.getCell(55,1).font={size:9,color:{argb:'FF555555'}};ws.pageSetup.printArea='A1:W55';ws.headerFooter.oddFooter='&LCodex Analytics — Office Hero Pack&RPage &P of &N'}
function buildMonthlySheet(wb,name,y,m){const ws=wb.addWorksheet(name,{pageSetup:{orientation:'portrait',paperSize:state.pageSize==='Legal'?5:1,fitToPage:true,fitToWidth:1,fitToHeight:1,margins:{left:.35,right:.35,top:.4,bottom:.4,header:.15,footer:.15}}});ws.mergeCells('A1:G1');setCell(ws.getCell('A1'),`${MONTHS[m]} ${y} — ${state.name}`,{bold:true,size:15,color:'FFFFFFFF',fill:'FF0D223B'});DOW.forEach((x,i)=>setCell(ws.getCell(2,i+1),x,{bold:true,fill:'FFECEFF2'}));const first=new Date(y,m,1),days=new Date(y,m+1,0).getDate(),off=(first.getDay()+6)%7;for(let d=1;d<=days;d++){const idx=off+d-1,r=3+Math.floor(idx/7),c=1+(idx%7),ev=eventsOn(y,m,d);setCell(ws.getCell(r,c),String(d)+(ev.length?'\n'+ev.map(e=>e.name).join('\n'):''),{align:'left'});ws.getRow(r).height=55}let r=10;ws.mergeCells(r,1,r,7);setCell(ws.getCell(r,1),'Event Details',{bold:true,color:'FFFFFFFF',fill:'FF142F50'});r++;const pre=`${y}-${String(m+1).padStart(2,'0')}`;for(const c of state.categories){const es=activeEvents().filter(e=>e.categoryId===c.id&&e.startDate.startsWith(pre));if(!es.length)continue;ws.mergeCells(r,1,r,7);setCell(ws.getCell(r,1),c.name,{bold:true,color:'FFFFFFFF',fill:excelColor(c.color),align:'left'});r++;for(const e of es){ws.mergeCells(r,1,r,7);setCell(ws.getCell(r,1),`${fmt(e.startDate)} — ${e.name}${e.org?` [${e.org}]`:''}${e.description?`\n${e.description}`:''}`,{align:'left'});ws.getRow(r).height=e.description?34:22;r++}}for(let c=1;c<=7;c++)ws.getColumn(c).width=15;ws.pageSetup.printArea=`A1:G${Math.max(r,12)}`;ws.headerFooter.oddFooter='&LCodex Analytics — Office Hero Pack&RPage &P of &N'}
async function exportClipboard(){if(!window.ExcelJS)return alert('Excel library failed to load.');const wb=new ExcelJS.Workbook(),ws=wb.addWorksheet('Calendar Events');ws.addRow(['Event ID','Event Name','Grant / Organization','Category','Status','Start Date','End Date','Description','Notes','Suggested Clipboard Trigger']);for(const e of state.events)ws.addRow([e.id,e.name,e.org,cat(e.categoryId).name,e.status,e.startDate,e.endDate,e.description,e.notes,suggestTrigger(e)]);ws.getRow(1).font={bold:true,color:{argb:'FFFFFFFF'}};ws.getRow(1).fill={type:'pattern',pattern:'solid',fgColor:{argb:'FF0D223B'}};ws.columns=[20,30,24,28,14,14,14,40,40,55].map(width=>({width}));const q=wb.addWorksheet('Decision Tree Seeds');q.addRows([['Category','Example questions for Clipboard Tool'],['Grant Events / Deadlines','What data must be collected? | Are financial documents required? | Who must review/approve? | What attachments are required? | What internal draft and QA dates are needed?'],['Site Visits','What records must be prepared? | Who must attend? | Does the facility need preparation? | What evidence should be available? | Is a pre-visit team briefing needed?'],['Grant Meetings / Trainings','Is registration required? | Who should attend? | What should be reviewed beforehand? | Are questions/materials needed? | Is follow-up documentation required?'],['Holidays / Organization Days','Does this closure affect a deadline? | Must work be completed earlier? | Are stakeholders aware of the closure?']]);q.getColumn(1).width=30;q.getColumn(2).width=110;download(new Blob([await wb.xlsx.writeBuffer()],{type:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'}),'Office_Hero_Clipboard_Sample_Data.xlsx')}
function suggestTrigger(e){if(isSiteCat(e.categoryId))return e.status==='tentative'?'Site visit window announced: identify preparation tasks once date is confirmed.':'Confirmed site visit: generate preparation, evidence, staffing, and follow-up tasks.';if(/deadline/i.test(cat(e.categoryId).name))return 'Deadline: generate data collection, drafting, review, approval, QA, and submission tasks.';if(/meeting|training/i.test(cat(e.categoryId).name))return 'Meeting/training: generate registration, preparation, attendance, materials, and follow-up tasks.';return 'Review whether this date creates prerequisite or follow-up work.'}
init();
